language: go
sudo: false

go:
  - "1.15"
  - "1.16"
  - master

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v
  - go build
  - $HOME/gopath/bin/goveralls -service=travis-ci
